Use `@wordpress/env` (wp-env) for local dev environment

diff --git a/.github/workflows/continuous-integration-e2e.yml b/.github/workflows/continuous-integration-e2e.yml
--- a/.github/workflows/continuous-integration-e2e.yml
+++ b/.github/workflows/continuous-integration-e2e.yml
@@ -18,20 +18,26 @@ jobs:
     runs-on: ubuntu-latest
     strategy:
       matrix:
-        # TODO: add back Firefox once support is more mature.
         include:
           - browser: 'chrome'
             wp: 'latest'
-            coverage: true
+            snapshots: true
+
           - browser: 'chrome'
             wp: '5.3.6'
-            coverage: false
+            snapshots: false
+    env:
+      WP_BASE_URL: http://localhost:8899
 
     steps:
       - name: Checkout
         uses: actions/checkout@v2
 
-      # See https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#chrome-headless-doesnt-launch-on-unix
+        # See https://github.com/WordPress/gutenberg/issues/22398
+      - name: Install libkrb5-dev
+        run: sudo apt-get install libkrb5-dev
+
+        # See https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#chrome-headless-doesnt-launch-on-unix
       - name: Install libgbm1
         run: sudo apt-get install libgbm1
 
@@ -58,7 +64,7 @@ jobs:
         uses: shivammathur/setup-php@v2
         with:
           php-version: '7.4'
-          coverage: none
+          snapshots: none
           tools: composer:v1
 
       - name: Get Composer cache directory
@@ -88,25 +94,51 @@ jobs:
           # TODO: remove eventually
           DISABLE_PREVENT: true
 
-      - name: Start Docker environment
-        run: npm run env:start
+      - name: Configure WordPress version
+        run: |
+          if [[ $WP_VERSION == 'master' ]]; then
+            echo "Using WordPress version: $WP_VERSION"
+
+            echo "{\"core\":\"WordPress/WordPress#${WP_VERSION}\"}" >> .wp-env.override.json
+            exit 0
+          fi
+
+          if [[ $WP_VERSION == 'latest' ]]; then
+            LATEST_VERSION=$(curl -s http://api.wordpress.org/core/version-check/1.7/ | jq -r '.offers[0].version')
+            if [[ -z "$LATEST_VERSION" ]]; then
+              echo "Latest WordPress version could not be found"
+              exit 1
+            fi
+
+            echo "Found latest WordPress version: $LATEST_VERSION"
+            WP_VERSION=$LATEST_VERSION
+          fi
+
+          echo "Using WordPress version: $WP_VERSION"
+
+          echo "{\"core\":\"WordPress/WordPress#tags/${WP_VERSION}\"}" >> .wp-env.override.json
         env:
-          COMPOSE_INTERACTIVE_NO_CLI: true
           WP_VERSION: ${{ matrix.wp }}
+
+      - name: Start Docker environment
+        run: |
+          chmod -R 767 ./
+          npm run wp-env start -- --update --debug
+
+      - name: Prepare E2E tests
+        run: npm run test:e2e:prepare
 
       - name: Run E2E tests with percy
         run: npm run test:e2e:percy
         env:
           PERCY_TOKEN: ${{ secrets.PERCY_TOKEN_E2E }}
           PUPPETEER_PRODUCT: ${{ matrix.browser }}
-        if: ( matrix.coverage ) && ( github.event.pull_request.draft == false )
+        if: ( matrix.snapshots ) && ( github.event.pull_request.draft == false )
 
       - name: Run E2E tests
         run: npm run test:e2e
-        if: ( ! matrix.coverage ) || ( github.event.pull_request.draft == true )
+        if: ( ! matrix.snapshots ) || ( github.event.pull_request.draft == true )
 
       - name: Stop Docker environment
-        run: npm run env:stop
-        if: always()
-        env:
-          COMPOSE_INTERACTIVE_NO_CLI: true
+        run: npm run wp-env stop
+        if: ${{ success() || failure() }}
diff --git a/.github/workflows/continuous-integration-unit-php.yml b/.github/workflows/continuous-integration-unit-php.yml
--- a/.github/workflows/continuous-integration-unit-php.yml
+++ b/.github/workflows/continuous-integration-unit-php.yml
@@ -11,16 +11,6 @@ jobs:
   unit-php:
     name: 'PHP ${{ matrix.php }} - WP ${{ matrix.wp }}'
     runs-on: ubuntu-latest
-    services:
-      mysql:
-        image: mariadb:latest
-        env:
-          MYSQL_ALLOW_EMPTY_PASSWORD: true
-          MYSQL_ROOT_PASSWORD:
-          MYSQL_DATABASE: wordpress_test
-        ports:
-          - 3306
-        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
     continue-on-error: ${{ matrix.experimental == true }}
     strategy:
       matrix:
@@ -35,16 +25,43 @@ jobs:
           - php: '5.6'
             wp: '5.3'
 
-          - php: '8.0'
-            wp: 'latest'
+          # Disabled until 8.0 Docker image is available.
+          #
+          #          - php: '8.0'
+          #            wp: 'latest'
 
           - php: '7.4'
-            wp: 'trunk'
+            wp: 'master'
             experimental: true
 
     steps:
       - name: Checkout
         uses: actions/checkout@v2
+
+      - name: Read .nvmrc
+        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
+        id: nvm
+
+      - name: Setup Node
+        uses: actions/setup-node@v2.1.2
+        with:
+          node-version: '${{ steps.nvm.outputs.NVMRC }}'
+
+      - name: Setup npm cache
+        uses: pat-s/always-upload-cache@v2.1.3
+        with:
+          path: node_modules
+          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
+          restore-keys: |
+            ${{ runner.os }}-npm-${{ env.cache-name }}-
+            ${{ runner.os }}-npm-
+            ${{ runner.os }}-
+
+      - name: Install dependencies
+        run: npm ci
+        env:
+          CI: true
+          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
 
       - name: Get Composer cache directory
         id: composer-cache
@@ -78,35 +95,55 @@ jobs:
         uses: shivammathur/setup-php@v2
         with:
           php-version: ${{ matrix.php }}
-          extensions: mysql
-          coverage: xdebug
           tools: composer:v1, cs2pr
+
+        # TODO: Remove "latest" special case. See https://github.com/WordPress/gutenberg/issues/27763
+      - name: Configure WordPress version
+        run: |
+          if [[ $WP_VERSION == 'master' ]]; then
+            echo "Using WordPress version: $WP_VERSION"
+
+            echo "{\"core\":\"WordPress/WordPress#${WP_VERSION}\"}" >> .wp-env.override.json
+            exit 0
+          fi
+
+          if [[ $WP_VERSION == 'latest' ]]; then
+            LATEST_VERSION=$(curl -s http://api.wordpress.org/core/version-check/1.7/ | jq -r '.offers[0].version')
+            if [[ -z "$LATEST_VERSION" ]]; then
+              echo "Latest WordPress version could not be found"
+              exit 1
+            fi
+
+            echo "Found latest WordPress version: $LATEST_VERSION"
+            WP_VERSION=$LATEST_VERSION
+          fi
+
+          echo "Using WordPress version: $WP_VERSION"
+
+          echo "{\"core\":\"WordPress/WordPress#tags/${WP_VERSION}\"}" >> .wp-env.override.json
+
+          echo "Installing matching version of wp-phpunit/wp-phpunit"
+
+          composer require --prefer-dist --no-suggest --no-progress --no-interaction --no-scripts --dev wp-phpunit/wp-phpunit:${WP_VERSION}
+        env:
+          WP_VERSION: ${{ matrix.wp }}
 
       - name: Install dependencies
         run: |
           composer install --prefer-dist --no-suggest --no-progress --no-interaction --no-scripts
           composer dump-autoload --no-interaction
 
-      - name: Shutdown default MySQL service
-        run: sudo service mysql stop
+      - name: Start Docker environment
+        run: npm run wp-env start -- --update
+        env:
+          WP_ENV_PHP_VERSION: ${{ matrix.php }}
+        if: ${{ ! matrix.coverage }}
 
-      - name: Verify MariaDB connection
-        run: |
-          while ! mysqladmin ping -h"127.0.0.1" -P"${{ job.services.mysql.ports[3306] }}" --silent; do
-            sleep 1
-          done
-
-      - name: Set up tests
-        run: bash bin/install-wp-tests.sh wordpress_test root '' 127.0.0.1:${{ job.services.mysql.ports['3306'] }} ${{ matrix.wp }} true
-
-      # 1. Installs PHPUnit 7.5 and patches it to run on PHP 8.
-      # 2. Dumps autoloader so mcaskill/composer-plugin-exclude-files is triggered.
-      - name: Update PHPUnit
-        run: |
-          composer require --dev --ignore-platform-reqs --no-interaction --no-scripts --update-with-all-dependencies phpunit/phpunit:^7.5
-          git apply patches/composer.patch
-          composer dump-autoload --no-interaction
-        if: ${{ matrix.php == '8.0' }}
+      - name: Start Docker environment with Xdebug
+        run: npm run wp-env start -- --update --xdebug=coverage
+        env:
+          WP_ENV_PHP_VERSION: ${{ matrix.php }}
+        if: ${{ matrix.coverage }}
 
       - name: Run tests
         run: |
@@ -116,8 +153,8 @@ jobs:
 
       - name: Run tests with coverage
         run: |
-          npm run test:php -- --coverage-clover build/logs/php-coverage.xml
-          npm run test:php -- --coverage-clover build/logs/php-coverage-multisite.xml -c phpunit-multisite.xml.dist
+          npm run test:php:coverage
+          npm run test:php:multisite:coverage
         if: ${{ matrix.coverage }}
 
       - name: Upload code coverage report
@@ -125,3 +162,7 @@ jobs:
         with:
           file: build/logs/*.xml
         if: ${{ matrix.coverage }}
+
+      - name: Stop Docker environment
+        run: npm run wp-env stop
+        if: ${{ success() || failure() }}
